### ISSUE TITLE
Unable to trigger cron job

### ISSUE THREAD

**Issue by cxnky** [IoTSharp/SilkierQuartz#153]
Hi, I have a cron job that didn't fire, so I tried manually running it through the UI, but I get an error 500 and the following error

 ```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerator`1<System.Collections.Generic.KeyValuePair`2<!0,!1>> Quartz.Util.DirtyFlagMap`2.GetEnumerator()'.
         at SilkierQuartz.Extensions.GetJobDataMapModelCore(Object jobOrTrigger, Services services)
         at SilkierQuartz.Extensions.GetJobDataMapModel(IJobDetail job, Services services)
         at SilkierQuartz.Controllers.JobsController.Trigger(String name, String group)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
```
         

SilkierQuartz version: ``5.0.374``
Quartz version: ``3.13.0``

**Comment by YrendersSWD** [comment]
I have the same issue , how is it solved ?
